[common]
quit = ["ctrl-c"]
help = ["?"]
dump = ["f12"]

[bucket_list]
down = ["j"]
up = ["k"]
go_to_top = ["g"]
go_to_bottom = ["shift-g"]
page_down = ["ctrl-f"]
page_up = ["ctrl-b"]
select = ["enter"]

download = ["s"]
download_as = ["shift-s"]
filter = ["/"]
sort = ["o"]
copy_details = ["r"]
refresh = ["shift-r"]
reset_filter = ["esc"]
management_console = ["x"]

[object_list]
down = ["j"]
up = ["k"]
go_to_top = ["g"]
go_to_bottom = ["shift-g"]
page_down = ["ctrl-f"]
page_up = ["ctrl-b"]
select = ["enter"]
back = ["backspace"]
bucket_list = ["~"]

download = ["s"]
download_as = ["shift-s"]
filter = ["/"]
sort = ["o"]
copy_details = ["r"]
refresh = ["shift-r"]
reset_filter = ["esc"]
management_console = ["x"]

[object_detail]
down = ["j"]
up = ["k"]
right = ["l"]
left = ["h"]
go_to_top = ["g"]
go_to_bottom = ["shift-g"]
back = ["backspace"]

download = ["s"]
download_as = ["shift-s"]
preview = ["p"]
copy_details = ["r"]
management_console = ["x"]

[object_preview]
down = ["j"]
up = ["k"]
right = ["l"]
left = ["h"]
go_to_top = ["g"]
go_to_bottom = ["shift-g"]
page_down = ["ctrl-f"]
page_up = ["ctrl-b"]
back = ["backspace"]

download = ["s"]
download_as = ["shift-s"]
encoding = ["e"]
toggle_wrap = ["w"]
toggle_number = ["n"]

[help]
close = ["?", "backspace"]

# filter
[input_dialog]
close = ["esc"]
apply = ["enter"]

# sort, copy, encoding, confirm
[select_dialog]
down = ["j"]
up = ["k"]
right = ["l"]
left = ["h"]

close = ["esc"]
select = ["enter"]
