download_dir = './out/download'
default_region = 'us-east-1'

[ui.help]
max_help_width = 80

[preview]

highlight = true
image = true
encodings = ["utf-8", "utf-16be", "utf-16le", "sjis", "iso-2022-jp"]
